excludedPaths: # Directories to be neglected by the Hub's crawler
  - /drafts # Leading slash indicates root of repository
  - /.idea
  - /broken
  - /example_code
  - /opinionated-recipes
  - /group_review
cookbooks: # List of cookbooks
  - id: scw:basic-protection-set
    name: Basic Protection Set
    description: Cookbook which can be used as a starting point for security
    includedTags: [basic-protection-set] # In the future this would be replaced with specific vulnerability tags
    excludedTags: [] # In the future this would be replaced by 'framework-specific' to exclude those recipes
  - id: scw:java
    name: "Java Gotcha's"
    description: Examples of simple Java mistakes that can be easily detected and fixed with Sensei
    includedTags: [java-basic]
    excludedTags: []
#  - id: scw:recipes
#    name: All SCW Recipes
#    description: Collection of all recipes available
#    includedTags: [] # Should be interpreted as wildcard to retrieve all cookbooks
#    excludedTags: []
  - id: scw:aws
    name: AWS SDK
    description: Examples of best practices that can be easily detected and fixed with Sensei
    includedTags: [AWS]
    excludedTags: []
  - id: scw:spring
    name: Spring
    description: Collection of recipes related to Java Spring
    includedTags: [spring]
    excludedTags: []
#  - id: scw:crypto
#    name: Crypto
#    description: Collection of recipes related to Cryptography
#    includedTags: [crypto]
#    excludedTags: []
#  - id: scw:web
#    name: Web
#    description: Collection of recipes related to web applications
#    includedTags: [web]
#    excludedTags: []
#  - id: scw:xml
#    name: XML
#    description: Collection of recipes related to XML
#    includedTags: [XML,XXE]
#    excludedTags: [] # Should Spring recipes or other framework specific recipes be filtered?
#  - id: scw:snakeyaml
#    name: SnakeYAML
#    description: Collection of recipes related to YAML parsing using SnakeYAML
#    includedTags: [snakeyaml]
#    excludedTags: []
  - id: scw:android
    name: Android Security Set
    description: Recipes created from security recommendations in the official Android documentation (https://developer.android.com/)
    includedTags: [android-security-set]
    excludedTags: []
