# rootPaths specify which folders to scan for recipes.
# Recipes may specify 'descriptionFile' paths either relative to
# the recipe's location or relative to the rootPath.
rootPaths:
  - recipes
cookbooks: # List of cookbooks
  - id: scw:basic-protection-set
    name: Basic Protection Set
    description: Starting point for security that detects weak cryptography, injection vulnerabilities and XXE in a framework-agnostic way 
    includedTags: ["basic protection set"]
    excludedTags: []
  - id: scw:java
    name: "Java Gotcha's"
    description: Detection of mistakes relating to specific Java language features
    includedTags: ["Java basic"]
    excludedTags: []
  - id: scw:aws
    name: AWS SDK
    description: Best practices for the Amazon Web Services ecosystem
    includedTags: [AWS]
    excludedTags: []
  - id: scw:spring
    name: Spring
    description: Best practices related to the Java Spring projects
    includedTags: [Spring]
    excludedTags: []
  - id: scw:android
    name: Android Security Set
    description: Recipes created from security recommendations in the official Android documentation (https://developer.android.com/)
    includedTags: [Android security set]
    excludedTags: []
  - id: scw:owasp-top-10
    name: OWASP Top 10 Set
    description: Collection of all recipes related to the OWASP Top 10
    includedTags: [OWASP Top 10]
    excludedTags: []
