# rootPaths specify which folders to scan for recipes.
# Recipes may specify 'descriptionFile' paths either relative to
# the recipe's location or relative to the rootPath.
rootPaths:
  - recipes
cookbooks: # List of cookbooks
  - id: scw:basic-protection-set
    name: Basic Protection Set
    description: Starting point for security that detects weak cryptography, injection vulnerabilities and XXE in a framework-agnostic way. 
    includedTags: ["basic protection set"]
    excludedTags: []
    featured: true
    recommended: true
  - id: scw:java
    name: "Java Gotcha's"
    description: Detection of mistakes relating to incorrect or unsafe use of Java language features and APIs such as object equality, exception handling, regular expressions and collections.
    includedTags: ["Java basic"]
    excludedTags: []
    featured: true
    recommended: true
  - id: scw:aws
    name: AWS SDK
    description: Best practices for the Amazon Web Services ecosystem including credential management/storage, databases and region selection.
    includedTags: [AWS]
    excludedTags: []
    featured: true
  - id: scw:spring
    name: Spring
    description: Best practices spanning the Java Spring projects including Boot, Core, Data, Security and Web. 
    includedTags: [Spring]
    excludedTags: []
    featured: true
  - id: scw:android
    name: Android Security Set
    description: Recipes created from security recommendations in the official Android documentation (https://developer.android.com/), including checks for the manifest file, injection vulnerability, configuration and storage.  
    includedTags: [Android security set]
    excludedTags: []
    featured: true
  - id: scw:owasp-top-10
    name: OWASP Top 10 Set
    description: Collection of all recipes related to the OWASP Top 10 categories such as injection, authentication, security misconfiguration.
    includedTags: [OWASP Top 10]
    excludedTags: []
    featured: true
  - id: scw:logging:slf4j
    name: Standardisation on SLF4J
    description: Recipes to standardise on the SLF4J framework including migrations from other logging frameworks
    includedTags: [SLF4J]
    excludedTags: []
    featured: true
  - id: scw:testing:junit4
    name: JUnit 4 Best Practices
    description: Best practices for the JUnit 4 testing framework including correct usage of its API and annotations.
    includedTags: [JUnit 4]
    excludedTags: []
    featured: true
  - id: scw:testing:junit5
    name: JUnit 5 Best Practices
    description: Best practices for the JUnit 5 testing framework including correct usage of its API and annotations.
    includedTags: [JUnit 5]
    excludedTags: []
    featured: true
