id: scw:android:insecure-settings
version: 9
metadata:
  name: 'Android WebView best practices: Insecure settings'
  shortDescription: Enabling this WebView setting has security implications
  level: warning
  language: java
  enabled: true
  descriptionFile: descriptions/AndroidWebViewbestpractices.html
  tags: security;framework specific;Android;mobile;Android security set
search:
  methodcall:
    args:
      1:
        value:
          stringified: "true"
    name:
      matches: setJavaScriptEnabled|setAllowFileAccess|setGeolocationEnabled|setAllowContentAccess
    declaration:
      type: android.webkit.WebSettings
availableFixes:
- name: Change WebView setting to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
