id: scw:spring:security:stricthttpfirewall-null
version: 9
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Rule configuration: Reject (URL encoded) null'
  shortDescription: Rejecting the use of a (URL encoded) null is more secure
  level: warning
  language: java
  enabled: true
  descriptionFile: descriptions/RejectURLEncodedNull.html
  tags: Spring;security;framework specific;Spring Security;web
search:
  methodcall:
    args:
      1:
        type: boolean
        value:
          stringified: "true"
    name: setAllowNull
    type: org.springframework.security.web.firewall.StrictHttpFirewall
availableFixes:
- name: Set setAllowNull to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
