id: scw:spring:security:stricthttpfirewall-semicolon
version: 8
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Rule configuration: Reject
    semicolon'
  shortDescription: Rejecting semicolons is more secure
  level: warning
  language: java
  enabled: true
  descriptionFile: descriptions/RejectSemicolons.html
  tags: spring;security;framework-specific;web;spring-security
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "true"
    name: setAllowSemicolon
    type: org.springframework.security.web.firewall.StrictHttpFirewall
availableFixes:
- name: Set setAllowSemicolon to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
