id: scw:java:equality-wrappers
version: 8
metadata:
  name: Incorrect equality check of wrapper values
  shortDescription: Use equals method to compare wrapped values
  level: error
  language: java
  scwCategory: blog:generic
  cweCategory: 480
  enabled: true
  tags: default;java-basic;quality
search:
  comparison:
    anyOf:
    - operator: ==
    - operator: '!='
    first:
      expression:
        type:
          reference:
            anyOf:
            - is: java.lang.Short
            - is: java.lang.Integer
            - is: java.lang.Long
          checkInheritance: true
    second:
      expression:
        type:
          reference:
            anyOf:
            - is: java.lang.Short
            - is: java.lang.Integer
            - is: java.lang.Long
          checkInheritance: true
availableFixes:
- name: Check equality using equals
  actions:
  - rewrite:
      to: '{{{leftOperand}}}.equals({{{rightOperand}}})'
