id: scw:java:equality-wrappers-not-equals
version: 10
metadata:
  name: Incorrect equality check of wrapper values (not equals)
  shortDescription: Use equals method to compare wrapped values
  level: error
  language: java
  scwCategory: blog:generic
  cweCategory: 480
  enabled: true
  descriptionFile: descriptions/Incorrect_equality_check_of_wrapper_values.html
  tags: Java basic;quality;SEI CERT
search:
  comparison:
    first:
      expression:
        type:
          reference:
            matches: java\.lang\.(Character|Float|Integer|Long|Short|Double)
          checkInheritance: true
    operator: '!='
    second:
      expression:
        type:
          reference:
            matches: java\.lang\.(Character|Float|Integer|Long|Short|Double)
          checkInheritance: true
availableFixes:
- name: Check equality using equals
  actions:
  - rewrite:
      to: '!{{{leftOperand}}}.equals({{{rightOperand}}})'
