id: scw:java:equality-wrappers
version: 9
metadata:
  name: Incorrect equality check of wrapper values
  shortDescription: Use equals method to compare wrapped values
  level: error
  language: java
  scwCategory: blog:generic
  cweCategory: 480
  enabled: true
  descriptionFile: descriptions/Incorrect_equality_check_of_wrapper_values.html
  tags: Java basic;quality
search:
  comparison:
    anyOf:
    - operator: ==
    - operator: '!='
    first:
      expression:
        type:
          reference:
            matches: java\.lang\.(Boolean|Byte|Character|Float|Integer|Long|Short|Double)
          checkInheritance: true
    second:
      expression:
        type:
          reference:
            matches: java\.lang\.(Boolean|Byte|Character|Float|Integer|Long|Short|Double)
          checkInheritance: true
availableFixes:
- name: Check equality using equals
  actions:
  - rewrite:
      to: '{{{leftOperand}}}.equals({{{rightOperand}}})'
