id: scw:web:csrf-disabled
version: 8
metadata:
  name: 'CSRF: Disabled in WebSecurityConfigurator'
  shortDescription: CSRF protection is disabled
  level: info
  language: java
  scwCategory: csrf
  enabled: true
  tags: security;web;CSRF
search:
  methodcall:
    name: disable
    "on":
      methodcall:
        name: csrf
availableFixes: []
